# mypy global options:
[tool.mypy]
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
python_executable="venv/bin/python"

[tool.pyright]
venvPath = "."
venv = "venv"

[tool.ruff]
line-length = 120

[tool.ruff.lint.pycodestyle]
max-line-length = 120
